package love.you.dao;


import love.you.po.ProductInfo;

public interface ProductInfoDao {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbggenerated Thu Apr 05 21:57:29 CST 2018
     */
    int insert(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbggenerated Thu Apr 05 21:57:29 CST 2018
     */
    int insertSelective(ProductInfo record);


}